<?php
return array(
    'testuser'=>array(
        'method'=>'GET',
        'call'=>'Test/UserInfoTest/index'
    ),
    'testorders'=>array(
        'method'=>'GET',
        'call'=>'Test/OrdersTest/index'
    ),
    'testpage'=>array(
        'method'=>'GET',
        'call'=>'Test/UserInfoTest/page'
    ),
    'testaddadmin'=>array(
        'method'=>'GET',
        'call'=>'Test/TestAdmin/insert'
    ),
    'testcreatepri'=>array(
        'method'=>'GET',
        'call'=>'Test/CreatePrivileges/index'
    ),
    'testcreaterou'=>array(
        'method'=>'GET',
        'call'=>'Test/CreateStruct/router'
    ),
    'testcreatelog'=>array(
        'method'=>'GET',
        'call'=>'Test/CreateStruct/logic'
    ),
    'testcreatecon'=>array(
        'method'=>'GET',
        'call'=>'Test/CreateStruct/controller'
    ),
    'testimpexc'=>array(
        'method'=>'GET',
        'call'=>'Test/ImportExcel/index'
    )
);